In [1]:
import numpy as np

# Creating numbers from 10 to 100 with a gap of 10
data = np.arange(10, 101, 10)

print(data)

[ 10  20  30  40  50  60  70  80  90 100]


In [2]:
# Creating a 3x4 array filled with zeros
zeros = np.zeros((3, 4))

print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
data = np.array([10, 20, 30, 40, 50])

# Checking the basic properties of the array
print("ndim:", data.ndim)
print("shape:", data.shape)
print("size:", data.size)
print("dtype:", data.dtype)

ndim: 1
shape: (5,)
size: 5
dtype: int32


In [4]:
data = np.array([10, 20, 30, 40, 50])

# Getting the last value from the array
print(data[-1])

50


In [5]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Selecting all rows and the first two columns
print(data[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [6]:
# Creating 12 numbers first
data = np.arange(1, 13)

# Changing the array into a 3x4 matrix
matrix = data.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Transposing the matrix changes rows into columns
print(data.T)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
data = np.array([1, 2, 3, 4, 5])

# Multiplying every value in the array by 5
result = data * 5

print(result)

[ 5 10 15 20 25]


In [9]:
import numpy as np

# Creating 5 samples with 3 features
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [15, 25, 35],
    [45, 55, 65]
])

# Checking the number of rows and columns
print("Shape:", X.shape)

Shape: (5, 3)


In [10]:
# Finding the average value of each feature
feature_mean = np.mean(X, axis=0)

print("Feature means:", feature_mean)

Feature means: [36. 46. 56.]


In [11]:
# Selecting rows where the first feature is greater than 50
filtered_rows = X[X[:, 0] > 50]

print(filtered_rows)

[[70 80 90]]


In [12]:
# Finding the mean and standard deviation of each feature
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

# Standardizing each feature column
X_standardized = (X - mean) / std

print("Standardized data:")
print(X_standardized)

Standardized data:
[[-1.19421955 -1.19421955 -1.19421955]
 [ 0.18372608  0.18372608  0.18372608]
 [ 1.56167172  1.56167172  1.56167172]
 [-0.96456195 -0.96456195 -0.96456195]
 [ 0.41338369  0.41338369  0.41338369]]


In [13]:
# Setting a seed so we get the same random values every time
np.random.seed(42)

# Creating a random matrix with 10 rows and 4 columns
random_matrix = np.random.rand(10, 4)

print(random_matrix)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]


In [14]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

weights = np.array([0.2, 0.3, 0.5])

# Multiplying the features with their corresponding weights
result = X @ weights

print(result)

[23. 53. 83.]


In [15]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

bias = np.array([1, 2, 3])

# Adding the bias to each row
result = X + bias

print(result)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [16]:
y_true = np.array([10, 20, 30, 40])
y_pred = np.array([12, 18, 33, 37])

# Finding the difference between actual and predicted values
error = y_true - y_pred

# Calculating the mean squared error
mse = np.mean(error ** 2)

print("MSE:", mse)

MSE: 6.5


In [17]:
import numpy as np

# Creating a 28x28 grayscale image
image = np.zeros((28, 28))

print("Image shape:", image.shape)

Image shape: (28, 28)


In [18]:
# Creating 64 RGB images of size 224x224
images = np.zeros((64, 224, 224, 3))

print("Images shape:", images.shape)

Images shape: (64, 224, 224, 3)


In [19]:
data = np.array([10, 20, np.nan, 40, 50])

# Calculating the mean while ignoring the NaN value
mean_value = np.nanmean(data)

print("NaN-safe mean:", mean_value)

NaN-safe mean: 30.0


In [20]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Multiplying corresponding elements
elementwise_result = A * B

# Performing matrix multiplication
matrix_result = A @ B

print("A * B:")
print(elementwise_result)

print("A @ B:")
print(matrix_result)

A * B:
[[ 5 12]
 [21 32]]
A @ B:
[[19 22]
 [43 50]]


In [21]:
import numpy as np

data = np.array([10, 20, 30, 40, 50], dtype=float)

# Scaling the values between 0 and 1
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

# Standardizing the values using mean and standard deviation
standardized = (data - np.mean(data)) / np.std(data)

print("Original:", data)
print("Normalized:", normalized)
print("Standardized:", standardized)

# Checking the mean and standard deviation after standardization
print("Standardized mean:", np.mean(standardized))
print("Standardized std:", np.std(standardized))

Original: [10. 20. 30. 40. 50.]
Normalized: [0.   0.25 0.5  0.75 1.  ]
Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Standardized mean: 0.0
Standardized std: 0.9999999999999999
